---
- name: install_all
  hosts: "{{ h }}"
  become: yes
  gather_facts: no
  tasks:

  - name: install python git pip3
    apt:
      name: [ "python3", "git", "python3-pip" ]
      state: present
      update_cache: yes

  - name: copy ssh
    copy:
      src: "../keys/id_rsa"
      dest: /home/ubuntu/.ssh/

  - name: copy env files
    copy:
      src: "antispam-bot.env"
      dest: /home/ubuntu/


  - name: copy env files 2
    copy:
      src: "kaztili-bot.env"
      dest: /home/ubuntu/

  - name: copy env files 3
    copy:
      src: "runcalc-bot.env"
      dest: /home/ubuntu/

  - name: clone repo 1
    git:
      repo: git@github.com:snvtr/antispam-bot.git
      dest: /home/ubuntu/antispam-bot
      key_file: "/home/ubuntu/.ssh/id_rsa"
      ssh_opts: "-o StrictHostKeyChecking=no"

  - name: clone repo 1
    git:
      repo:
      - "https://github.com/snvtr/KaztiliSozdikBot.git"
      dest: /home/ubuntu/KaztiliSozdikBot
      key_file: "/home/ubuntu/.ssh/id_rsa"
      ssh_opts: "-o StrictHostKeyChecking=no"

  - name: clone repo 3
    git:
      repo:
      - "https://github.com/snvtr/runcalc-bot.git"
      dest: /home/ubuntu/runcalc-bot
      key_file: "/home/ubuntu/.ssh/id_rsa"
      ssh_opts: "-o StrictHostKeyChecking=no"

        # pip goes here

  - name: copy challenge.py
    copy:
      src: [ "antispam-bot/challenge.py" ]
      dest: /etc/systemd/system/
    notify:
      systemd_daemon_reload

  - name: copy service files
    copy:
      src: [ "antispam-bot/antispam-bot.service", "KaztiliSozdikBot/kaztili-bot.service", "runcalc-bot/runcalc-bot.env" ]
      dest: /etc/systemd/system/
    notify:
      systemd_daemon_reload

  handlers:
  - name: systemd_daemon_reload
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: haproxy
