---
- name: install_all
  hosts: all
  become: yes
  gather_facts: no
  tasks:

  - name: install python git pip3
    apt:
      name: [ "python3", "git", "python3-pip" ]
      state: present
      update: yes

  - name: copy env files
    copy:
      src: [ "files/antispam-bot.env", "files/kaztili-bot.env", "files/runcalc-bot.env" ]
      dest: /home/ubuntu/

  - name: clone repos
    git:
      repo: [ "https://github.com/snvtr/antispam-bot.git", "https://github.com/snvtr/KaztiliSozdikBot.git", "https://github.com/snvtr/runcalc-bot.git" ]
      dest: /home/ubuntu/

  - name: copy challenge.py
    copy:
      src: [ "antispam-bot/challenge.py" ]
      dest: /etc/systemd/system/
    notify:
      systemd_daemon_reload

  - name: copy service files
    copy:
      src: [ "antispam-bot/antispam-bot.service", "KaztiliSozdikBot/kaztili-bot.service", "runcalc-bot/runcalc-bot.env" ]
      dest: /etc/systemd/system/
    notify:
      systemd_daemon_reload

  handlers:
  - name: systemd_daemon_reload
    systemd:
      state: restarted
      enabled: yes
      daemon_reload: yes
      name: haproxy
